### ISSUE TITLE
Parallel evaluations

### ISSUE THREAD

**Issue by rix0rrr** [darwins-challenge/moonlander-ast-rust#5]
Here's a supposedly good library to get the most out of our available CPUs

https://github.com/nikomatsakis/rayon/

**Comment by dvberkel** [comment]
From the README :-)

> WARNING: Rayon is still in experimental status. It is probably not very robust and not (yet) suitable for production applications. In particular, the handling of panics is known to be terrible. See nikomatsakis/rayon#10 for more details.

Interesting though it that nikomatsakis/rayon#10 is closed.

**Comment by rix0rrr** [comment]
Meh. We're not production. We're cool!

**Comment by dvberkel** [comment]
Then I am cool by association
